### PR TITLE
Accessors

### PR DESCRIPTION
**Pull request by tonystone**
This pull request represents the addition of the **Accessors** for all the geometry classes (issue #11).  It also represents a major change in the inheritance hierarchy as depicted below. 

geofeatures-inheritance-diagram

The design is a more natural representation of the objects in question.  When implementing the design, some compromise in static type safety was introduced due to 'Objective-C's lack of **function overloading**<sup>[1](#footnote-1)</sup> support. Specifically, the interface to `GFGeometryCollection` has been defined using `id` which allows any class to be passed. Defining it this way was thought to be a good compromise given that all subclasses are statically typed and enforceable at compile time. Also, new features in iOS 9 will allow us to gain the static safety for `GFGeometryCollection` in the near future (these can't be mentioned here until after public release, Sept 16th).

For clarity the `GFGeometryCollection` interface is defined as follows:

``` Objective-C
@interface GFGeometryCollection  : GFGeometry

    - (NSUInteger)   count;
    - (id) geometryAtIndex: (NSUInteger) index;
    - (id) firstGeometry;
    - (id) lastGeometry;

@end
```

And `GFMultiPoint` is defined as:

``` Objective-C
@interface GFMultiPoint  : GFGeometryCollection

    - (NSUInteger)   count;
    - (GFPoint *) geometryAtIndex: (NSUInteger) index;
    - (GFPoint *) firstGeometry;
    - (GFPoint *) lastGeometry;

@end
```

A **`GFRing`** type has been added to support the internal representation of `GFPolygon`.  It now supports methods `outerRing` and `innerRings`.  This class is a direct subclass of `'GFLineString` and represents a **closed** `GFLineString`.

Several classes in the old hierarchy have been deprecated (`GFPointAbstract`, `GFLineStringAbstract`, and `GFPolygonAbstract`) with the intention of removing them in version 2.  These classes where never meant to be used directly and if they we're not replied on the change in the hierarchy should not affect existing uses of the library.
#### Foot Notes

<a name="footnote-1">[1]</a>: Objective-C' does not support **function overloading**. An overloaded declaration is a declaration that had been declared with the same name as a previously declared declaration in the same scope, except that both declarations have different arguments and obviously different definition (implementation). This is due to the fact that "Objective-C" does **not** include the parameter types as the signature of the method.

Instead "Objective-C" forces you to name each method within the same namespace uniquely.

### CODE REVIEW

**Comment by tonystone** [comment]
There is one open issue at the moment.  I define the interface for getting the number of objects in a collection as simply `count` where as all other methods for the collection are either prefixed or suffixed with the type (e.g. `geometryAtIndex:`, `firstGeometry`, etc).

The question is should `count` change to `geometryCount` or stay the same.  An alternative is to leave `count` as is and change the other methods dropping the type prefix and suffix.  so we get the following interfaces. So the options are.

#### Leaving `count` alone:

``` Objective-C
@interface GFGeometryCollection  : GFGeometry

    - (NSUInteger)   count;
    - (id) geometryAtIndex: (NSUInteger) index;
    - (id) firstGeometry;
    - (id) lastGeometry;

@end
```

The above is a lot like the NSArray interface only it replaces 'geometry' with 'object' in the names (e.g. `objectAtIndex:` and it still uses `count` for the number of objects.

#### Changing `count`:

``` Objective-C
@interface GFGeometryCollection  : GFGeometry

    - (NSUInteger)   geometryCount;
    - (id) geometryAtIndex: (NSUInteger) index;
    - (id) firstGeometry;
    - (id) lastGeometry;

@end
```

#### Changing the other method names:

``` Objective-C
@interface GFGeometryCollection  : GFGeometry

    - (NSUInteger)  count;
    - (id) atIndex: (NSUInteger) index;
    - (id) first;
    - (id) last;

@end
```

cc: @tommy

**Comment by tommy** [comment]
I think the first option (that mirrors the NSArray interface) is the most natural. I think the asymmetry between the "count" method name and the others actually makes sense because the count method returns an integer, while the others return geometries (so they have geometry in the name, giving an indication what the "id" type really is).

I understand where you're coming from though, and geometryCount would be a fine interface too, IMO. This is just my preference!

**Comment by tonystone** [comment]
@tommy I agree, I'll merge the PR as is.

**Comment by jklimaat** [comment]
Nice addition, Tony. And I agree with Tommy's suggestion for keeping the first option.

**Pull request merged**
